[package]
name = "gwar"
version = "0.0.1"
authors = ["Matthew Dillon <matthewrdillon@gmail.com>"]
edition = "2018"

[dependencies]
git2 = "0.13"
serde = { version = "1.0", features = ["derive"] }
shellexpand = "2.1"
toml = "0.5"
